//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VOFWebService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kana.com/dforms", ConfigurationName="VOFWebService.service")]
    public interface service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kana.com/dforms/AttachFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VOFWebService.AttachFileResponse1> AttachFileAsync(VOFWebService.AttachFileRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kana.com/dforms/GetFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VOFWebService.GetFileResponse1> GetFileAsync(VOFWebService.GetFileRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kana.com/dforms/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VOFWebService.UpdateResponse1> UpdateAsync(VOFWebService.UpdateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kana.com/dforms/List", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VOFWebService.ListResponse1> ListAsync(VOFWebService.ListRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kana.com/dforms/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VOFWebService.CreateResponse1> CreateAsync(VOFWebService.CreateRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kana.com/dforms/RemoveFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VOFWebService.RemoveFileResponse1> RemoveFileAsync(VOFWebService.RemoveFileRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kana.com/dforms/Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VOFWebService.GetResponse1> GetAsync(VOFWebService.GetRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kana.com/dforms/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<VOFWebService.DeleteResponse1> DeleteAsync(VOFWebService.DeleteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://kana.com/dforms/ReplaceCustomerid")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task ReplaceCustomeridAsync(VOFWebService.ReplaceCustomeridRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class AttachFileRequest
    {
        
        private string refField;
        
        private string filenameField;
        
        private string fileField;
        
        private string mimetypeField;
        
        private string fieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mimetype
        {
            get
            {
                return this.mimetypeField;
            }
            set
            {
                this.mimetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kana.com/dforms")]
    public partial class Form
    {
        
        private string nameField;
        
        private int versionField;
        
        private string refField;
        
        private int currentpageField;
        
        private string customeridField;
        
        private string organisationidField;
        
        private string propertyidField;
        
        private string streetidField;
        
        private string interactionidField;
        
        private string emailField;
        
        private string caseidField;
        
        private string xrefField;
        
        private string xref1Field;
        
        private string xref2Field;
        
        private int retrycountField;
        
        private string completeField;
        
        private string authsuppliedField;
        
        private string localeField;
        
        private System.DateTime createdField;
        
        private System.DateTime modifiedField;
        
        private Data dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int currentpage
        {
            get
            {
                return this.currentpageField;
            }
            set
            {
                this.currentpageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string customerid
        {
            get
            {
                return this.customeridField;
            }
            set
            {
                this.customeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string organisationid
        {
            get
            {
                return this.organisationidField;
            }
            set
            {
                this.organisationidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string propertyid
        {
            get
            {
                return this.propertyidField;
            }
            set
            {
                this.propertyidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string streetid
        {
            get
            {
                return this.streetidField;
            }
            set
            {
                this.streetidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string interactionid
        {
            get
            {
                return this.interactionidField;
            }
            set
            {
                this.interactionidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string caseid
        {
            get
            {
                return this.caseidField;
            }
            set
            {
                this.caseidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string xref
        {
            get
            {
                return this.xrefField;
            }
            set
            {
                this.xrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string xref1
        {
            get
            {
                return this.xref1Field;
            }
            set
            {
                this.xref1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string xref2
        {
            get
            {
                return this.xref2Field;
            }
            set
            {
                this.xref2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int retrycount
        {
            get
            {
                return this.retrycountField;
            }
            set
            {
                this.retrycountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string complete
        {
            get
            {
                return this.completeField;
            }
            set
            {
                this.completeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string authsupplied
        {
            get
            {
                return this.authsuppliedField;
            }
            set
            {
                this.authsuppliedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public Data data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kana.com/dforms")]
    public partial class Data
    {
        
        private Field[] formdataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("form-data", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("field", IsNullable=false)]
        public Field[] formdata
        {
            get
            {
                return this.formdataField;
            }
            set
            {
                this.formdataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kana.com/dforms")]
    public partial class Field
    {
        
        private string nameField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("children", typeof(Children), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("value", typeof(string), Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("values", typeof(Values), Order=1)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kana.com/dforms")]
    public partial class Children
    {
        
        private Field[][] childField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("field", typeof(Field[]), IsNullable=false)]
        public Field[][] child
        {
            get
            {
                return this.childField;
            }
            set
            {
                this.childField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kana.com/dforms")]
    public partial class Values
    {
        
        private string[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("value", Order=0)]
        public string[] value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kana.com/dforms")]
    public partial class File
    {
        
        private string refField;
        
        private string filenameField;
        
        private string fileField;
        
        private string mimetypeField;
        
        private string fieldField;
        
        private string localeField;
        
        private System.DateTime createdField;
        
        private System.DateTime modifiedField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mimetype
        {
            get
            {
                return this.mimetypeField;
            }
            set
            {
                this.mimetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                this.modifiedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class AttachFileResponse
    {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AttachFileRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.AttachFileRequest AttachFileRequest;
        
        public AttachFileRequest1()
        {
        }
        
        public AttachFileRequest1(VOFWebService.AttachFileRequest AttachFileRequest)
        {
            this.AttachFileRequest = AttachFileRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AttachFileResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.AttachFileResponse AttachFileResponse;
        
        public AttachFileResponse1()
        {
        }
        
        public AttachFileResponse1(VOFWebService.AttachFileResponse AttachFileResponse)
        {
            this.AttachFileResponse = AttachFileResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class GetFileRequest
    {
        
        private string refField;
        
        private string filenameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class GetFileResponse
    {
        
        private File fileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public File File
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.GetFileRequest GetFileRequest;
        
        public GetFileRequest1()
        {
        }
        
        public GetFileRequest1(VOFWebService.GetFileRequest GetFileRequest)
        {
            this.GetFileRequest = GetFileRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.GetFileResponse GetFileResponse;
        
        public GetFileResponse1()
        {
        }
        
        public GetFileResponse1(VOFWebService.GetFileResponse GetFileResponse)
        {
            this.GetFileResponse = GetFileResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class UpdateRequest
    {
        
        private string nameField;
        
        private string refField;
        
        private string versionField;
        
        private string customeridField;
        
        private string organisationidField;
        
        private string propertyidField;
        
        private string streetidField;
        
        private string interactionidField;
        
        private string emailField;
        
        private string passwordField;
        
        private string caseidField;
        
        private string xrefField;
        
        private string xref1Field;
        
        private string xref2Field;
        
        private string currentpageField;
        
        private stringBoolean completeField;
        
        private bool completeFieldSpecified;
        
        private string retrycountField;
        
        private Data dataField;
        
        private dataupdate dataupdateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string customerid
        {
            get
            {
                return this.customeridField;
            }
            set
            {
                this.customeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string organisationid
        {
            get
            {
                return this.organisationidField;
            }
            set
            {
                this.organisationidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string propertyid
        {
            get
            {
                return this.propertyidField;
            }
            set
            {
                this.propertyidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string streetid
        {
            get
            {
                return this.streetidField;
            }
            set
            {
                this.streetidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string interactionid
        {
            get
            {
                return this.interactionidField;
            }
            set
            {
                this.interactionidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string caseid
        {
            get
            {
                return this.caseidField;
            }
            set
            {
                this.caseidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string xref
        {
            get
            {
                return this.xrefField;
            }
            set
            {
                this.xrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string xref1
        {
            get
            {
                return this.xref1Field;
            }
            set
            {
                this.xref1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string xref2
        {
            get
            {
                return this.xref2Field;
            }
            set
            {
                this.xref2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=14)]
        public string currentpage
        {
            get
            {
                return this.currentpageField;
            }
            set
            {
                this.currentpageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public stringBoolean complete
        {
            get
            {
                return this.completeField;
            }
            set
            {
                this.completeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completeSpecified
        {
            get
            {
                return this.completeFieldSpecified;
            }
            set
            {
                this.completeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=16)]
        public string retrycount
        {
            get
            {
                return this.retrycountField;
            }
            set
            {
                this.retrycountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public Data data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public dataupdate dataupdate
        {
            get
            {
                return this.dataupdateField;
            }
            set
            {
                this.dataupdateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kana.com/dforms")]
    public enum stringBoolean
    {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kana.com/dforms")]
    public enum dataupdate
    {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        clear,
        
        /// <remarks/>
        overwrite,
        
        /// <remarks/>
        merge,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class UpdateResponse
    {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.UpdateRequest UpdateRequest;
        
        public UpdateRequest1()
        {
        }
        
        public UpdateRequest1(VOFWebService.UpdateRequest UpdateRequest)
        {
            this.UpdateRequest = UpdateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.UpdateResponse UpdateResponse;
        
        public UpdateResponse1()
        {
        }
        
        public UpdateResponse1(VOFWebService.UpdateResponse UpdateResponse)
        {
            this.UpdateResponse = UpdateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class ListRequest
    {
        
        private string customeridField;
        
        private string organisationidField;
        
        private string nameField;
        
        private stringBoolean completeField;
        
        private bool completeFieldSpecified;
        
        private options optionField;
        
        private bool optionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string customerid
        {
            get
            {
                return this.customeridField;
            }
            set
            {
                this.customeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string organisationid
        {
            get
            {
                return this.organisationidField;
            }
            set
            {
                this.organisationidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public stringBoolean complete
        {
            get
            {
                return this.completeField;
            }
            set
            {
                this.completeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completeSpecified
        {
            get
            {
                return this.completeFieldSpecified;
            }
            set
            {
                this.completeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public options option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optionSpecified
        {
            get
            {
                return this.optionFieldSpecified;
            }
            set
            {
                this.optionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://kana.com/dforms")]
    public enum options
    {
        
        /// <remarks/>
        all,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class ListResponse
    {
        
        private Form[] formsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Form[] Forms
        {
            get
            {
                return this.formsField;
            }
            set
            {
                this.formsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.ListRequest ListRequest;
        
        public ListRequest1()
        {
        }
        
        public ListRequest1(VOFWebService.ListRequest ListRequest)
        {
            this.ListRequest = ListRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.ListResponse ListResponse;
        
        public ListResponse1()
        {
        }
        
        public ListResponse1(VOFWebService.ListResponse ListResponse)
        {
            this.ListResponse = ListResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class CreateRequest
    {
        
        private string nameField;
        
            private string customeridField;
        
            private string organisationidField;
        
            private string propertyidField;
        
            private string streetidField;
        
            private string interactionidField;
        
            private string emailField;
        
            private string passwordField;
        
        private string caseidField;
        
            private string xrefField;
        
            private string xref1Field;
        
            private string xref2Field;
        
        private Data dataField;
        
        private stringBoolean completeField;
        
        private bool completeFieldSpecified;
        
        private string localeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string customerid
        {
            get
            {
                return this.customeridField;
            }
            set
            {
                this.customeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string organisationid
        {
            get
            {
                return this.organisationidField;
            }
            set
            {
                this.organisationidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string propertyid
        {
            get
            {
                return this.propertyidField;
            }
            set
            {
                this.propertyidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string streetid
        {
            get
            {
                return this.streetidField;
            }
            set
            {
                this.streetidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string interactionid
        {
            get
            {
                return this.interactionidField;
            }
            set
            {
                this.interactionidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string caseid
        {
            get
            {
                return this.caseidField;
            }
            set
            {
                this.caseidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string xref
        {
            get
            {
                return this.xrefField;
            }
            set
            {
                this.xrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string xref1
        {
            get
            {
                return this.xref1Field;
            }
            set
            {
                this.xref1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string xref2
        {
            get
            {
                return this.xref2Field;
            }
            set
            {
                this.xref2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Data data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public stringBoolean complete
        {
            get
            {
                return this.completeField;
            }
            set
            {
                this.completeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completeSpecified
        {
            get
            {
                return this.completeFieldSpecified;
            }
            set
            {
                this.completeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class CreateResponse
    {
        
        private string statusField;
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.CreateRequest CreateRequest;
        
        public CreateRequest1()
        {
        }
        
        public CreateRequest1(VOFWebService.CreateRequest CreateRequest)
        {
            this.CreateRequest = CreateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.CreateResponse CreateResponse;
        
        public CreateResponse1()
        {
        }
        
        public CreateResponse1(VOFWebService.CreateResponse CreateResponse)
        {
            this.CreateResponse = CreateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class RemoveFileRequest
    {
        
        private string refField;
        
        private string filenameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string filename
        {
            get
            {
                return this.filenameField;
            }
            set
            {
                this.filenameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class RemoveFileResponse
    {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveFileRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.RemoveFileRequest RemoveFileRequest;
        
        public RemoveFileRequest1()
        {
        }
        
        public RemoveFileRequest1(VOFWebService.RemoveFileRequest RemoveFileRequest)
        {
            this.RemoveFileRequest = RemoveFileRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveFileResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.RemoveFileResponse RemoveFileResponse;
        
        public RemoveFileResponse1()
        {
        }
        
        public RemoveFileResponse1(VOFWebService.RemoveFileResponse RemoveFileResponse)
        {
            this.RemoveFileResponse = RemoveFileResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class GetRequest
    {
        
        private string refField;
        
        private options optionField;
        
        private bool optionFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public options option
        {
            get
            {
                return this.optionField;
            }
            set
            {
                this.optionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool optionSpecified
        {
            get
            {
                return this.optionFieldSpecified;
            }
            set
            {
                this.optionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class GetResponse
    {
        
        private string nameField;
        
        private int versionField;
        
        private string refField;
        
        private int currentpageField;
        
        private string customeridField;
        
        private string propertyidField;
        
        private string streetidField;
        
        private string organisationidField;
        
        private string interactionidField;
        
        private string emailField;
        
        private string caseidField;
        
        private string xrefField;
        
        private string xref1Field;
        
        private string xref2Field;
        
        private int retrycountField;
        
        private string completeField;
        
        private string localeField;
        
        private string authsuppliedField;
        
        private System.DateTime createdField;
        
        private System.DateTime modifiedField;
        
        private Data dataField;
        
        private File[] filesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int currentpage
        {
            get
            {
                return this.currentpageField;
            }
            set
            {
                this.currentpageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string customerid
        {
            get
            {
                return this.customeridField;
            }
            set
            {
                this.customeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string propertyid
        {
            get
            {
                return this.propertyidField;
            }
            set
            {
                this.propertyidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string streetid
        {
            get
            {
                return this.streetidField;
            }
            set
            {
                this.streetidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string organisationid
        {
            get
            {
                return this.organisationidField;
            }
            set
            {
                this.organisationidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string interactionid
        {
            get
            {
                return this.interactionidField;
            }
            set
            {
                this.interactionidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string caseid
        {
            get
            {
                return this.caseidField;
            }
            set
            {
                this.caseidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string xref
        {
            get
            {
                return this.xrefField;
            }
            set
            {
                this.xrefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string xref1
        {
            get
            {
                return this.xref1Field;
            }
            set
            {
                this.xref1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string xref2
        {
            get
            {
                return this.xref2Field;
            }
            set
            {
                this.xref2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int retrycount
        {
            get
            {
                return this.retrycountField;
            }
            set
            {
                this.retrycountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string complete
        {
            get
            {
                return this.completeField;
            }
            set
            {
                this.completeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string locale
        {
            get
            {
                return this.localeField;
            }
            set
            {
                this.localeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string authsupplied
        {
            get
            {
                return this.authsuppliedField;
            }
            set
            {
                this.authsuppliedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public System.DateTime created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public System.DateTime modified
        {
            get
            {
                return this.modifiedField;
            }
            set
            {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public Data data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=21)]
        [System.Xml.Serialization.XmlArrayItemAttribute("file", IsNullable=false)]
        public File[] files
        {
            get
            {
                return this.filesField;
            }
            set
            {
                this.filesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.GetRequest GetRequest;
        
        public GetRequest1()
        {
        }
        
        public GetRequest1(VOFWebService.GetRequest GetRequest)
        {
            this.GetRequest = GetRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.GetResponse GetResponse;
        
        public GetResponse1()
        {
        }
        
        public GetResponse1(VOFWebService.GetResponse GetResponse)
        {
            this.GetResponse = GetResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class DeleteRequest
    {
        
        private string refField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string @ref
        {
            get
            {
                return this.refField;
            }
            set
            {
                this.refField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class DeleteResponse
    {
        
        private string statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.DeleteRequest DeleteRequest;
        
        public DeleteRequest1()
        {
        }
        
        public DeleteRequest1(VOFWebService.DeleteRequest DeleteRequest)
        {
            this.DeleteRequest = DeleteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.DeleteResponse DeleteResponse;
        
        public DeleteResponse1()
        {
        }
        
        public DeleteResponse1(VOFWebService.DeleteResponse DeleteResponse)
        {
            this.DeleteResponse = DeleteResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://kana.com/dforms")]
    public partial class ReplaceCustomeridRequest
    {
        
        private string customeridField;
        
        private string[] replaceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string customerid
        {
            get
            {
                return this.customeridField;
            }
            set
            {
                this.customeridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("customerid", IsNullable=false)]
        public string[] replace
        {
            get
            {
                return this.replaceField;
            }
            set
            {
                this.replaceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReplaceCustomeridRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://kana.com/dforms", Order=0)]
        public VOFWebService.ReplaceCustomeridRequest ReplaceCustomeridRequest;
        
        public ReplaceCustomeridRequest1()
        {
        }
        
        public ReplaceCustomeridRequest1(VOFWebService.ReplaceCustomeridRequest ReplaceCustomeridRequest)
        {
            this.ReplaceCustomeridRequest = ReplaceCustomeridRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface serviceChannel : VOFWebService.service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class serviceClient : System.ServiceModel.ClientBase<VOFWebService.service>, VOFWebService.service
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public serviceClient() : 
                base(serviceClient.GetDefaultBinding(), serviceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.serviceSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviceClient(EndpointConfiguration endpointConfiguration) : 
                base(serviceClient.GetBindingForEndpoint(endpointConfiguration), serviceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(serviceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(serviceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VOFWebService.AttachFileResponse1> VOFWebService.service.AttachFileAsync(VOFWebService.AttachFileRequest1 request)
        {
            return base.Channel.AttachFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<VOFWebService.AttachFileResponse1> AttachFileAsync(VOFWebService.AttachFileRequest AttachFileRequest)
        {
            VOFWebService.AttachFileRequest1 inValue = new VOFWebService.AttachFileRequest1();
            inValue.AttachFileRequest = AttachFileRequest;
            return ((VOFWebService.service)(this)).AttachFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VOFWebService.GetFileResponse1> VOFWebService.service.GetFileAsync(VOFWebService.GetFileRequest1 request)
        {
            return base.Channel.GetFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<VOFWebService.GetFileResponse1> GetFileAsync(VOFWebService.GetFileRequest GetFileRequest)
        {
            VOFWebService.GetFileRequest1 inValue = new VOFWebService.GetFileRequest1();
            inValue.GetFileRequest = GetFileRequest;
            return ((VOFWebService.service)(this)).GetFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VOFWebService.UpdateResponse1> VOFWebService.service.UpdateAsync(VOFWebService.UpdateRequest1 request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<VOFWebService.UpdateResponse1> UpdateAsync(VOFWebService.UpdateRequest UpdateRequest)
        {
            VOFWebService.UpdateRequest1 inValue = new VOFWebService.UpdateRequest1();
            inValue.UpdateRequest = UpdateRequest;
            return ((VOFWebService.service)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VOFWebService.ListResponse1> VOFWebService.service.ListAsync(VOFWebService.ListRequest1 request)
        {
            return base.Channel.ListAsync(request);
        }
        
        public System.Threading.Tasks.Task<VOFWebService.ListResponse1> ListAsync(VOFWebService.ListRequest ListRequest)
        {
            VOFWebService.ListRequest1 inValue = new VOFWebService.ListRequest1();
            inValue.ListRequest = ListRequest;
            return ((VOFWebService.service)(this)).ListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VOFWebService.CreateResponse1> VOFWebService.service.CreateAsync(VOFWebService.CreateRequest1 request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<VOFWebService.CreateResponse1> CreateAsync(VOFWebService.CreateRequest CreateRequest)
        {
            VOFWebService.CreateRequest1 inValue = new VOFWebService.CreateRequest1();
            inValue.CreateRequest = CreateRequest;
            return ((VOFWebService.service)(this)).CreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VOFWebService.RemoveFileResponse1> VOFWebService.service.RemoveFileAsync(VOFWebService.RemoveFileRequest1 request)
        {
            return base.Channel.RemoveFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<VOFWebService.RemoveFileResponse1> RemoveFileAsync(VOFWebService.RemoveFileRequest RemoveFileRequest)
        {
            VOFWebService.RemoveFileRequest1 inValue = new VOFWebService.RemoveFileRequest1();
            inValue.RemoveFileRequest = RemoveFileRequest;
            return ((VOFWebService.service)(this)).RemoveFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VOFWebService.GetResponse1> VOFWebService.service.GetAsync(VOFWebService.GetRequest1 request)
        {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<VOFWebService.GetResponse1> GetAsync(VOFWebService.GetRequest GetRequest)
        {
            VOFWebService.GetRequest1 inValue = new VOFWebService.GetRequest1();
            inValue.GetRequest = GetRequest;
            return ((VOFWebService.service)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VOFWebService.DeleteResponse1> VOFWebService.service.DeleteAsync(VOFWebService.DeleteRequest1 request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<VOFWebService.DeleteResponse1> DeleteAsync(VOFWebService.DeleteRequest DeleteRequest)
        {
            VOFWebService.DeleteRequest1 inValue = new VOFWebService.DeleteRequest1();
            inValue.DeleteRequest = DeleteRequest;
            return ((VOFWebService.service)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task VOFWebService.service.ReplaceCustomeridAsync(VOFWebService.ReplaceCustomeridRequest1 request)
        {
            return base.Channel.ReplaceCustomeridAsync(request);
        }
        
        public System.Threading.Tasks.Task ReplaceCustomeridAsync(VOFWebService.ReplaceCustomeridRequest ReplaceCustomeridRequest)
        {
            VOFWebService.ReplaceCustomeridRequest1 inValue = new VOFWebService.ReplaceCustomeridRequest1();
            inValue.ReplaceCustomeridRequest = ReplaceCustomeridRequest;
            return ((VOFWebService.service)(this)).ReplaceCustomeridAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.serviceSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.serviceSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://scnverinttest:9081/service");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return serviceClient.GetBindingForEndpoint(EndpointConfiguration.serviceSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return serviceClient.GetEndpointAddress(EndpointConfiguration.serviceSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            serviceSoap11,
        }
    }
}
